% MATLAB + JAGS script to perform a hierarchical linear
% regression to estimate initial growth rate (r) for
% Zika virus disease outbreak in Colombia 2015/2016

clear; clc;

% Retrieve observations from CSV file. Skip the first
% row since that row contains column names. After
% retrieval, extract the individual columns as separate
% variables. Note that we transform the case totals
% by taking the natural log.
observations = csvread('dept_totals.csv', 1, 0);
group = observations(:,1);
x     = observations(:,2);
y     = log(observations(:,3));

% Because our data is coded with the initial x-value of 0,
% we have observed intercept values for each group.
% Extact those values so that can be passed to JAGS.
y0 = y(x == 0);
intercept(1:max(group)) = 0;
for i = group(x == 0)
    intercept(i) = y0(find(group(x == 0) == i));
end

% Create the data structure for JAGS.
data = struct( ...
    'group',     group, ...
    'x',         x, ...
    'y',         y, ...
    'intercept', intercept ...
);

% Define initial values for the non-stochastic model
% parameters. Since there are none, this is an empty
% structure.
initial_values(1) = struct;

% Perform the MCMC analysis
[samples, stats, structArray] = matjags( ...
    data, ...
    fullfile(pwd, 'zika_regression.bug'), ...
    initial_values, ...
    'doparallel' ,    0, ...
    'nchains',        1, ...
    'nburnin',        1000, ...
    'nsamples',       10000, ...
    'thin',           1, ...
    'dic',            0, ...
    'monitorparams',  { ...
       'alpha', 'beta', 'beta_mu', 'pvalue', 'si', 'R0' ...
     }, ...
    'savejagsoutput', 1, ...
    'verbosity',      2, ...
    'cleanup',        1, ...
    'rndseed',        0 ...
);

% Use the estimated parameters to calculate predicted values
% and save results in a CSV file.
% for i = 1:length(y)
%     predicted(i) = stats.mean.alpha(group(i)) + ...
%         stats.mean.beta(group(i)) * x(i);
% end
% csvwrite('predicted.csv', [group'; x'; exp(y'); exp(predicted')]');

% Save R0 estimates in csv file
R0 = zeros(0,4);
for j = (group(x == 0))'
    row(1) = j;
    row(2) = stats.ci_low.R0(j);
    row(3) = stats.mean.R0(j);
    row(4) = stats.ci_high.R0(j);
    R0 = [R0; row];
end
% csvwrite('R0.csv', R0);
